/* generated by scripts/contract-to-host/gen.mjs -- 请勿手改：改契约后重生成 */
/* contract: contract.csv  rows: 8  digest: 4e49d1ad1055083f */
/* 本文件不含生成时间与绝对路径 ⇒ 同一契约两次生成逐字节一致 */

#ifndef CONTRACT_REGS_H
#define CONTRACT_REGS_H

#include <stdint.h>

/* 编译期断言：条件为假时报错数组（不依赖 C11 关键字） */
#define GEN_ASSERT(cond, tag) typedef char gen_assert_##tag[(cond) ? 1 : -1]

/* CTRL —— 总开关与运行使能  policy: bit0=en */
#define CTRL_OFFSET  0x00u
#define CTRL_WIDTH   32u
#define CTRL_RESET   0x00000001u
#define CTRL_ACCESS  ("RW")
#define CTRL_MASK    0xffffffffu
#define CTRL_READ(base) ((*(const volatile uint32_t *)((const uint8_t *)(base) + CTRL_OFFSET)))
#define CTRL_WRITE(base, v) ((*(volatile uint32_t *)((uint8_t *)(base) + CTRL_OFFSET)) = ((uint32_t)((v) & CTRL_MASK)))

/* STATUS —— 状态字（只读）  policy: 低 16 位为帧计数 */
#define STATUS_OFFSET  0x04u
#define STATUS_WIDTH   32u
#define STATUS_RESET   0x00000000u
#define STATUS_ACCESS  ("RO")
#define STATUS_MASK    0xffffffffu
#define STATUS_READ(base) ((*(const volatile uint32_t *)((const uint8_t *)(base) + STATUS_OFFSET)))
/* STATUS_WRITE: 故意不生成 —— RO 没有写宏是第一道防线 */

/* IE —— 中断使能掩码  policy: 按位使能 */
#define IE_OFFSET  0x08u
#define IE_WIDTH   32u
#define IE_RESET   0x00000000u
#define IE_ACCESS  ("RW")
#define IE_MASK    0xffffffffu
#define IE_READ(base) ((*(const volatile uint32_t *)((const uint8_t *)(base) + IE_OFFSET)))
#define IE_WRITE(base, v) ((*(volatile uint32_t *)((uint8_t *)(base) + IE_OFFSET)) = ((uint32_t)((v) & IE_MASK)))

/* ISC —— 中断挂起（读回后自动清零）  policy: W1C 读即清 */
#define ISC_OFFSET  0x0cu
#define ISC_WIDTH   8u
#define ISC_RESET   0x00000000u
#define ISC_ACCESS  ("self-clear")
#define ISC_MASK    0x000000ffu
#define ISC_READ(base) ((*(const volatile uint8_t *)((const uint8_t *)(base) + ISC_OFFSET)))
#define ISC_WRITE(base, v) ((*(volatile uint8_t *)((uint8_t *)(base) + ISC_OFFSET)) = ((uint8_t)((v) & ISC_MASK)))
/* ISC: self-clear —— 读即清，主机侧不许把读回值当状态缓存 */

/* DBG —— 调试计数（单位见 policy）  policy: tick = raw * 2 */
#define DBG_OFFSET  0x10u
#define DBG_WIDTH   16u
#define DBG_RESET   0x00000000u
#define DBG_ACCESS  ("RO")
#define DBG_MASK    0x0000ffffu
#define DBG_READ(base) ((*(const volatile uint16_t *)((const uint8_t *)(base) + DBG_OFFSET)))
/* DBG_WRITE: 故意不生成 —— RO 没有写宏是第一道防线 */

/* DAC —— 输出档位  policy: mv = count * 0.8 */
#define DAC_OFFSET  0x18u
#define DAC_WIDTH   12u
#define DAC_RESET   0x00000000u
#define DAC_ACCESS  ("RW")
#define DAC_MASK    0x00000fffu
#define DAC_READ(base) ((*(const volatile uint16_t *)((const uint8_t *)(base) + DAC_OFFSET)))
#define DAC_WRITE(base, v) ((*(volatile uint16_t *)((uint8_t *)(base) + DAC_OFFSET)) = ((uint16_t)((v) & DAC_MASK)))

/* SCRATCH —— 暂存寄存器（写什么读什么）  policy: raw */
#define SCRATCH_OFFSET  0x1cu
#define SCRATCH_WIDTH   32u
#define SCRATCH_RESET   0xffffffffu
#define SCRATCH_ACCESS  ("RW")
#define SCRATCH_MASK    0xffffffffu
#define SCRATCH_READ(base) ((*(const volatile uint32_t *)((const uint8_t *)(base) + SCRATCH_OFFSET)))
#define SCRATCH_WRITE(base, v) ((*(volatile uint32_t *)((uint8_t *)(base) + SCRATCH_OFFSET)) = ((uint32_t)((v) & SCRATCH_MASK)))

/* KEY —— 解锁口令（只写、无读回口）  policy: 写序列解锁 */
#define KEY_OFFSET  0x20u
#define KEY_WIDTH   32u
#define KEY_RESET   0x00000000u
#define KEY_ACCESS  ("WO")
#define KEY_MASK    0xffffffffu
#define KEY_READ(base) ((*(const volatile uint32_t *)((const uint8_t *)(base) + KEY_OFFSET)))
#define KEY_WRITE(base, v) ((*(volatile uint32_t *)((uint8_t *)(base) + KEY_OFFSET)) = ((uint32_t)((v) & KEY_MASK)))

/* ---- 编译期区间不重叠检查（按 offset 排序后的相邻对） ---- */
GEN_ASSERT((CTRL_OFFSET + ((CTRL_WIDTH + 7u) / 8u)) <= STATUS_OFFSET, cth_ov_1_CTRL_STATUS);
GEN_ASSERT((STATUS_OFFSET + ((STATUS_WIDTH + 7u) / 8u)) <= IE_OFFSET, cth_ov_2_STATUS_IE);
GEN_ASSERT((IE_OFFSET + ((IE_WIDTH + 7u) / 8u)) <= ISC_OFFSET, cth_ov_3_IE_ISC);
GEN_ASSERT((ISC_OFFSET + ((ISC_WIDTH + 7u) / 8u)) <= DBG_OFFSET, cth_ov_4_ISC_DBG);
GEN_ASSERT((DBG_OFFSET + ((DBG_WIDTH + 7u) / 8u)) <= DAC_OFFSET, cth_ov_5_DBG_DAC);
GEN_ASSERT((DAC_OFFSET + ((DAC_WIDTH + 7u) / 8u)) <= SCRATCH_OFFSET, cth_ov_6_DAC_SCRATCH);
GEN_ASSERT((SCRATCH_OFFSET + ((SCRATCH_WIDTH + 7u) / 8u)) <= KEY_OFFSET, cth_ov_7_SCRATCH_KEY);

/* ---- 编译期复位值不越界 ---- */
GEN_ASSERT((CTRL_RESET & ~CTRL_MASK) == 0u, cth_rst_CTRL);
GEN_ASSERT((STATUS_RESET & ~STATUS_MASK) == 0u, cth_rst_STATUS);
GEN_ASSERT((IE_RESET & ~IE_MASK) == 0u, cth_rst_IE);
GEN_ASSERT((ISC_RESET & ~ISC_MASK) == 0u, cth_rst_ISC);
GEN_ASSERT((DBG_RESET & ~DBG_MASK) == 0u, cth_rst_DBG);
GEN_ASSERT((DAC_RESET & ~DAC_MASK) == 0u, cth_rst_DAC);
GEN_ASSERT((SCRATCH_RESET & ~SCRATCH_MASK) == 0u, cth_rst_SCRATCH);
GEN_ASSERT((KEY_RESET & ~KEY_MASK) == 0u, cth_rst_KEY);

#endif /* CONTRACT_REGS_H */
