# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "<repo>/vivado_system/zynq_video_sys.runs/synth_1/system_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir <repo>/vivado_system/zynq_video_sys.cache/wt [current_project]
set_property parent.project_path <repo>/vivado_system/zynq_video_sys.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo <repo>/vivado_system/zynq_video_sys.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  <repo>/src/rtl/process/rotate/angle_ctrl.v
  <repo>/src/rtl/eth/arp.v
  <repo>/src/rtl/eth/arp_rx.v
  <repo>/src/rtl/eth/arp_tx.v
  <repo>/src/rtl/eth/axi_frame_saver64.v
  <repo>/src/rtl/axi/axi_frame_writer64.v
  <repo>/src/rtl/axi/axi_frame_writer_gated.v
  <repo>/src/rtl/process/bilin_lerp.v
  <repo>/src/rtl/clocks/clk_gen.v
  <repo>/src/rtl/process/rotate/cos_rom.v
  <repo>/src/rtl/eth/crc32_d8.v
  <repo>/src/rtl/eth/dc_fifo.v
  <repo>/src/rtl/eth/ddr_bank_commit.v
  <repo>/vivado_system/zynq_video_sys.gen/sources_1/bd/design_1/hdl/design_1_wrapper.v
  <repo>/src/rtl/process/effect_ctrl.v
  <repo>/src/rtl/eth/eth_ctrl.v
  <repo>/src/rtl/eth/eth_udp_video_top.v
  <repo>/src/rtl/process/bilin/fb_bilin.v
  <repo>/src/rtl/video/frame_buffer_w64.v
  <repo>/src/rtl/video/frame_commit_lock.v
  <repo>/src/rtl/video/frame_latency.v
  <repo>/src/rtl/eth/frame_reasm.v
  <repo>/src/rtl/video/gamma_lut.v
  <repo>/src/rtl/eth/gmii_rx_mac.v
  <repo>/src/rtl/eth/gmii_to_rgmii.v
  <repo>/src/rtl/eth/icmp.v
  <repo>/src/rtl/eth/icmp_rx.v
  <repo>/src/rtl/eth/icmp_tx.v
  <repo>/src/rtl/util/key_debounce.v
  <repo>/src/rtl/util/key_long.v
  <repo>/src/rtl/eth/link_monitor.v
  <repo>/src/rtl/video/osd_overlay.v
  <repo>/src/rtl/top/pl_video_top.v
  <repo>/src/rtl/process/proc_binary.v
  <repo>/src/rtl/process/proc_box_blur.v
  <repo>/src/rtl/process/proc_gray.v
  <repo>/src/rtl/process/proc_invert.v
  <repo>/src/rtl/process/proc_morph.v
  <repo>/src/rtl/process/proc_pipeline.v
  <repo>/src/rtl/process/proc_sharpen.v
  <repo>/src/rtl/process/proc_sobel.v
  <repo>/src/rtl/util/ps_publish.v
  <repo>/src/rtl/video/raw_line_delay.v
  <repo>/src/rtl/hdmi/rgb2dvi.v
  <repo>/src/rtl/eth/rgmii_rx.v
  <repo>/src/rtl/eth/rgmii_tx.v
  <repo>/src/rtl/video/seam_src.v
  <repo>/src/rtl/util/shown_rate.v
  <repo>/src/rtl/process/rotate/sin_rom.v
  <repo>/src/rtl/eth/snap_cross.v
  <repo>/src/rtl/video/split_ctrl.v
  <repo>/src/rtl/video/split_display.v
  <repo>/src/rtl/util/src_arb.v
  <repo>/src/rtl/util/src_life.v
  <repo>/src/rtl/util/src_mode.v
  <repo>/src/rtl/eth/sync_fifo.v
  <repo>/src/rtl/video/test_card.v
  <repo>/src/rtl/hdmi/tmds_encoder.v
  <repo>/src/rtl/hdmi/tmds_serializer.v
  <repo>/src/rtl/eth/udp_rx_parser.v
  <repo>/src/rtl/eth/udp_tx.v
  <repo>/src/rtl/video/video_timing.v
  <repo>/src/rtl/video/video_timing_1024x600.v
  <repo>/src/rtl/process/zoom/zoom_ctrl.v
  <repo>/src/rtl/process/zoom/zoom_fit.v
  <repo>/src/rtl/process/zoom/zoom_mapper.v
  <repo>/src/rtl/process/zoom/zoom_snap.v
  <repo>/src/rtl/top/system_top.v
}
add_files <repo>/vivado_system/zynq_video_sys.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all <repo>/vivado_system/zynq_video_sys.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all <repo>/vivado_system/zynq_video_sys.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all <repo>/vivado_system/zynq_video_sys.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all <repo>/vivado_system/zynq_video_sys.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all <repo>/vivado_system/zynq_video_sys.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all <repo>/vivado_system/zynq_video_sys.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all <repo>/vivado_system/zynq_video_sys.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all <repo>/vivado_system/zynq_video_sys.gen/sources_1/bd/design_1/ip/design_1_axi_gp0_ic_imp_xbar_0/design_1_axi_gp0_ic_imp_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all <repo>/vivado_system/zynq_video_sys.gen/sources_1/bd/design_1/ip/design_1_axi_gp0_ic_imp_auto_pc_0/design_1_axi_gp0_ic_imp_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all <repo>/vivado_system/zynq_video_sys.gen/sources_1/bd/design_1/design_1_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc <repo>/src/constraints/rk_zynq7020.xdc
set_property used_in_implementation false [get_files <repo>/src/constraints/rk_zynq7020.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top system_top -part xc7z020clg484-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file system_top_utilization_synth.rpt -pb system_top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
