// 用途：generated by scripts/contract-to-host/gen.mjs -- 每寄存器一条用例的骨架，期望值必须人填
// 输入：命令行参数
// 输出：stdout
// 退出码：2=NOT_MEASURED
// generated by scripts/contract-to-host/gen.mjs -- 每寄存器一条用例的骨架，期望值必须人填
// contract: contract.csv  rows: 8  digest: 4e49d1ad1055083f
// 纪律：期望没填 / 没注入 io / 契约缺列 / WO 无读回口 ⇒ NOT_MEASURED（exit 2），绝不判通过。
import { pathToFileURL } from 'node:url';
import { REGISTERS, offsetOf, isWritable, isSelfClear } from './contract_regs.mjs';

export const CASES = Object.freeze([
  Object.freeze({ reg: "CTRL", access: "RW",
    checks: ["写 A 读 A", "写 B 读 B"],
    reset: 0x00000001, policy: "bit0=en",
    expectA: "【待填：读回值】", expectB: "【待填：读回值】",
    contractMeasured: true }),
  Object.freeze({ reg: "STATUS", access: "RO",
    checks: ["RO 不可写（写后读回应不变）", "复位值读回"],
    reset: 0x00000000, policy: "低 16 位为帧计数",
    expectA: "【待填：读回值】", expectB: "【待填：读回值】",
    contractMeasured: true }),
  Object.freeze({ reg: "IE", access: "RW",
    checks: ["写 A 读 A", "写 B 读 B"],
    reset: 0x00000000, policy: "按位使能",
    expectA: "【待填：读回值】", expectB: "【待填：读回值】",
    contractMeasured: true }),
  Object.freeze({ reg: "ISC", access: "self-clear",
    checks: ["置位后读回应为 0（自清）", "二次读仍为 0"],
    reset: 0x00000000, policy: "W1C 读即清",
    expectA: "【待填：读回值】", expectB: "【待填：读回值】",
    contractMeasured: true }),
  Object.freeze({ reg: "DBG", access: "RO",
    checks: ["RO 不可写（写后读回应不变）", "复位值读回"],
    reset: 0x00000000, policy: "tick = raw * 2",
    expectA: "【待填：读回值】", expectB: "【待填：读回值】",
    contractMeasured: true }),
  Object.freeze({ reg: "DAC", access: "RW",
    checks: ["写 A 读 A", "写 B 读 B"],
    reset: 0x00000000, policy: "mv = count * 0.8",
    expectA: "【待填：读回值】", expectB: "【待填：读回值】",
    contractMeasured: true }),
  Object.freeze({ reg: "SCRATCH", access: "RW",
    checks: ["写 A 读 A", "写 B 读 B"],
    reset: 0xffffffff, policy: "raw",
    expectA: "【待填：读回值】", expectB: "【待填：读回值】",
    contractMeasured: true }),
  Object.freeze({ reg: "KEY", access: "WO",
    checks: ["写 A（无读回口，需旁路读数）"],
    reset: 0x00000000, policy: "写序列解锁",
    expectA: "【待填：读回值】", expectB: "【待填：读回值】",
    contractMeasured: true }),
]);
const filled = (v) => typeof v === "number" || (typeof v === "string" && !String(v).startsWith("【"));
export async function runAll(io) {
  const rows = []; let cmp = 0, red = 0, nm = 0;
  for (const c of CASES) {
    const say = (verdict, detail, done) => {
      rows.push({ reg: c.reg, verdict, detail, cmp: done || 0 });
      cmp += done || 0;
      if (verdict === "FAIL") red++; else if (verdict !== "PASS") nm++;
    };
    if (!c.contractMeasured) say("NOT_MEASURED", "契约缺列（offset/width/access/reset 未给全），不编默认值", 0);
    else if (!io) say("NOT_MEASURED", "未注入 io：需要 { read(name), write(name, v) }（板上代理或台架）", 0);
    else if (c.access === "WO") say("NOT_MEASURED", "WO 没有读回口，要另给旁路读数才算测到", 0);
    else if (!filled(c.expectA)) say("NOT_MEASURED", "期望值未填（仍是占位符）", 0);
    else if (!isWritable(c.reg)) {
      io.write(c.reg, c.expectA); const a = io.read(c.reg); const b = io.read(c.reg);
      let k = 1, ok = (a === b);
      if (filled(c.expectB)) { k++; ok = ok && (b === c.expectB); }
      say(ok ? "PASS" : "FAIL", "RO 写后两次读回应相等：" + a + " vs " + b, k);
    } else if (isSelfClear(c.reg)) {
      io.write(c.reg, c.expectA); const a = io.read(c.reg); const b = io.read(c.reg);
      say((a === 0 && b === 0) ? "PASS" : "FAIL", "自清位读回应为 0：第一次 " + a + " 第二次 " + b, 2);
    } else {
      io.write(c.reg, c.expectA); const a = io.read(c.reg);
      const expB = filled(c.expectB) ? c.expectB : c.expectA;
      io.write(c.reg, expB); const b = io.read(c.reg);
      say((a === c.expectA && b === expB) ? "PASS" : "FAIL",
        "写 A 读 A=" + (a === c.expectA) + " 写 B 读 B=" + (b === expB) + "（偏移 " + offsetOf(c.reg) + "）", 2);
    }
    void REGISTERS;
  }
  return { rows, cmp, red, nm };
}
const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) {
  const res = await runAll(null);
  for (const x of res.rows) console.log(x.reg + " " + x.verdict + " 比较=" + x.cmp + " " + x.detail);
  console.log("契约行数=" + CASES.length + " 生成用例数=" + res.rows.length +
    " 一致=" + (CASES.length === res.rows.length ? "PASS" : "FAIL"));
  const token = res.red ? "FAIL" : (res.nm ? "NOT_MEASURED" : "PASS");
  console.log("判 " + res.cmp + " 项 红=" + res.red + " 未测=" + res.nm + " " + token);
  process.exit(res.red ? 1 : (res.nm ? 2 : 0));
}
