// generated by scripts/contract-to-host/gen.mjs -- 请勿手改：改契约后重生成
// contract: contract.csv  rows: 8  digest: 4e49d1ad1055083f
// 缺列的字段值是 null（不是 0！）—— 0 会把"没测到"洗成"通过"。

export const CONTRACT = Object.freeze({
  file: "contract.csv", rows: 8, digest: "4e49d1ad1055083f",
  cols: "name,offset,width,access,policy,reset,doc"
});

export const REGISTERS = Object.freeze([
  Object.freeze({
    name: "CTRL", offset: 0, width: 32, bytes: 4,
    access: "RW", mask: 0xffffffff, reset: 0x00000001,
    policy: "bit0=en", doc: "总开关与运行使能",
    measured: true, missing: []
  }),
  Object.freeze({
    name: "STATUS", offset: 4, width: 32, bytes: 4,
    access: "RO", mask: 0xffffffff, reset: 0x00000000,
    policy: "低 16 位为帧计数", doc: "状态字（只读）",
    measured: true, missing: []
  }),
  Object.freeze({
    name: "IE", offset: 8, width: 32, bytes: 4,
    access: "RW", mask: 0xffffffff, reset: 0x00000000,
    policy: "按位使能", doc: "中断使能掩码",
    measured: true, missing: []
  }),
  Object.freeze({
    name: "ISC", offset: 12, width: 8, bytes: 1,
    access: "self-clear", mask: 0x000000ff, reset: 0x00000000,
    policy: "W1C 读即清", doc: "中断挂起（读回后自动清零）",
    measured: true, missing: []
  }),
  Object.freeze({
    name: "DBG", offset: 16, width: 16, bytes: 2,
    access: "RO", mask: 0x0000ffff, reset: 0x00000000,
    policy: "tick = raw * 2", doc: "调试计数（单位见 policy）",
    measured: true, missing: []
  }),
  Object.freeze({
    name: "DAC", offset: 24, width: 12, bytes: 2,
    access: "RW", mask: 0x00000fff, reset: 0x00000000,
    policy: "mv = count * 0.8", doc: "输出档位",
    measured: true, missing: []
  }),
  Object.freeze({
    name: "SCRATCH", offset: 28, width: 32, bytes: 4,
    access: "RW", mask: 0xffffffff, reset: 0xffffffff,
    policy: "raw", doc: "暂存寄存器（写什么读什么）",
    measured: true, missing: []
  }),
  Object.freeze({
    name: "KEY", offset: 32, width: 32, bytes: 4,
    access: "WO", mask: 0xffffffff, reset: 0x00000000,
    policy: "写序列解锁", doc: "解锁口令（只写、无读回口）",
    measured: true, missing: []
  }),
]);

const BY_NAME = new Map(REGISTERS.map((r) => [r.name, r]));
export function regOf(name) {
  const r = BY_NAME.get(name);
  if (!r) throw new Error("契约里没有 " + name + "（共 " + REGISTERS.length + " 条）");
  return r;
}
export function offsetOf(name) {
  const r = regOf(name);
  if (r.offset === null) throw new Error(name + " 的 offset 缺列 ⇒ NOT_MEASURED，不许编默认值");
  return r.offset;
}
export function bytesOf(name) { return regOf(name).bytes; }
export function maskOf(name) { return regOf(name).mask; }
export function resetOf(name) { return regOf(name).reset; }
export function accessOf(name) { return regOf(name).access; }
export function isWritable(name) { const a = regOf(name).access; return a === 'RW' || a === 'WO' || a === 'self-clear'; }
export function isSelfClear(name) { return regOf(name).access === 'self-clear'; }
export function names() { return REGISTERS.map((r) => r.name); }
export default REGISTERS;
